# Generated by Django 5.1.2 on 2024-10-11 20:04

from django.db import migrations, models

# arquivo gerado sozinho
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
